package com.my.bean;

// Generated 2014-3-7 19:32:19 by Hibernate Tools 3.4.0.CR1

/**
 * InfoAdmin generated by hbm2java
 */
public class Html implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer htmlid;
	private String html;
	private Link link;

	public Html() {
	}

	public Integer getHtmlid() {
		return htmlid;
	}

	public void setHtmlid(Integer htmlid) {
		this.htmlid = htmlid;
	}

	public String getHtml() {
		return html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	public Link getLink() {
		return link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

}
