package com.my.bean;

// Generated 2014-3-7 19:32:19 by Hibernate Tools 3.4.0.CR1

/**
 * InfoAdmin generated by hbm2java
 */
public class Link implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer linkid;
	private String link;
	private String html;
	private String regex;

	public Link() {
	}

	public Integer getLinkid() {
		return linkid;
	}

	public void setLinkid(Integer linkid) {
		this.linkid = linkid;
	}

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getHtml() {
		return html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	public String getRegex() {
		return regex;
	}

	public void setRegex(String regex) {
		this.regex = regex;
	}

}
