package com.my.bean;

import java.util.Date;

// Generated 2014-3-7 19:32:19 by Hibernate Tools 3.4.0.CR1

/**
 * Temp001 generated by hbm2java
 */
public class Temp001 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer temp001id;
	private Date date;
	private String f1;
	private String f2;
	private String f3;
	private String f4;
	private String f5;
	private String f6;
	private String f7;
	private String f8;
	private String f9;
	private String fa;
	private String fb;
	private String fc;
	private String fd;
	private String fe;
	private String ff;
	private String fg;
	private String fh;
	private String fi;
	private String fj;
	private String fk;
	private String fl;
	private String fm;
	private String fn;
	private String fo;
	private String fp;
	private String fq;
	private String fr;
	private String fs;
	private String ft;
	private String fu;
	private String fv;
	private String fw;
	private String fx;
	private String fy;
	private String fz;
	private String a1;
	private String a2;

	public Temp001() {
	}

	public Integer getTemp001id() {
		return this.temp001id;
	}

	public void setTemp001id(Integer temp001id) {
		this.temp001id = temp001id;
	}

	public String getF1() {
		return this.f1 == null ? "" : this.f1;
	}

	public void setF1(String f1) {
		this.f1 = f1;
	}

	public String getF2() {
		return this.f2 == null ? "" : this.f2;
	}

	public void setF2(String f2) {
		this.f2 = f2;
	}

	public String getF3() {
		return this.f3 == null ? "" : this.f3;
	}

	public void setF3(String f3) {
		this.f3 = f3;
	}

	public String getF4() {
		return this.f4 == null ? "" : this.f4;
	}

	public void setF4(String f4) {
		this.f4 = f4;
	}

	public String getF5() {
		return this.f5 == null ? "" : this.f5;
	}

	public void setF5(String f5) {
		this.f5 = f5;
	}

	public String getF6() {
		return this.f6 == null ? "" : this.f6;
	}

	public void setF6(String f6) {
		this.f6 = f6;
	}

	public String getF7() {
		return this.f7 == null ? "" : this.f7;
	}

	public void setF7(String f7) {
		this.f7 = f7;
	}

	public String getF8() {
		return this.f8 == null ? "" : this.f8;
	}

	public void setF8(String f8) {
		this.f8 = f8;
	}

	public String getF9() {
		return this.f9 == null ? "" : this.f9;
	}

	public void setF9(String f9) {
		this.f9 = f9;
	}

	public String getFa() {
		return this.fa == null ? "" : this.fa;
	}

	public void setFa(String fa) {
		this.fa = fa;
	}

	public String getFb() {
		return this.fb == null ? "" : this.fb;
	}

	public void setFb(String fb) {
		this.fb = fb;
	}

	public String getFc() {
		return this.fc == null ? "" : this.fc;
	}

	public void setFc(String fc) {
		this.fc = fc;
	}

	public String getFd() {
		return this.fd == null ? "" : this.fd;
	}

	public void setFd(String fd) {
		this.fd = fd;
	}

	public String getFe() {
		return this.fe == null ? "" : this.fe;
	}

	public void setFe(String fe) {
		this.fe = fe;
	}

	public String getFf() {
		return ff == null ? "" : this.ff;
	}

	public void setFf(String ff) {
		this.ff = ff;
	}

	public String getFg() {
		return this.fg == null ? "" : this.fg;
	}

	public void setFg(String fg) {
		this.fg = fg;
	}

	public String getFh() {
		return this.fh == null ? "" : this.fh;
	}

	public void setFh(String fh) {
		this.fh = fh;
	}

	public String getFi() {
		return this.fi == null ? "" : this.fi;
	}

	public void setFi(String fi) {
		this.fi = fi;
	}

	public String getFj() {
		return this.fj == null ? "" : this.fj;
	}

	public void setFj(String fj) {
		this.fj = fj;
	}

	public String getFk() {
		return this.fk == null ? "" : this.fk;
	}

	public void setFk(String fk) {
		this.fk = fk;
	}

	public String getFl() {
		return this.fl == null ? "" : this.fl;
	}

	public void setFl(String fl) {
		this.fl = fl;
	}

	public String getFm() {
		return this.fm == null ? "" : this.fm;
	}

	public void setFm(String fm) {
		this.fm = fm;
	}

	public String getFn() {
		return this.fn == null ? "" : this.fn;
	}

	public void setFn(String fn) {
		this.fn = fn;
	}

	public String getFo() {
		return this.fo == null ? "" : this.fo;
	}

	public void setFo(String fo) {
		this.fo = fo;
	}

	public String getFp() {
		return this.fp == null ? "" : this.fp;
	}

	public void setFp(String fp) {
		this.fp = fp;
	}

	public String getFq() {
		return this.fq == null ? "" : this.fq;
	}

	public void setFq(String fq) {
		this.fq = fq;
	}

	public String getFr() {
		return this.fr == null ? "" : this.fr;
	}

	public void setFr(String fr) {
		this.fr = fr;
	}

	public String getFs() {
		return this.fs == null ? "" : this.fs;
	}

	public void setFs(String fs) {
		this.fs = fs;
	}

	public String getFt() {
		return this.ft == null ? "" : this.ft;
	}

	public void setFt(String ft) {
		this.ft = ft;
	}

	public String getFu() {
		return this.fu == null ? "" : this.fu;
	}

	public void setFu(String fu) {
		this.fu = fu;
	}

	public String getFv() {
		return this.fv == null ? "" : this.fv;
	}

	public void setFv(String fv) {
		this.fv = fv;
	}

	public String getFw() {
		return this.fw == null ? "" : this.fw;
	}

	public void setFw(String fw) {
		this.fw = fw;
	}

	public String getFx() {
		return this.fx == null ? "" : this.fx;
	}

	public void setFx(String fx) {
		this.fx = fx;
	}

	public String getFy() {
		return this.fy == null ? "" : this.fy;
	}

	public void setFy(String fy) {
		this.fy = fy;
	}

	public String getFz() {
		return this.fz == null ? "" : this.fz;
	}

	public void setFz(String fz) {
		this.fz = fz;
	}

	public String getA1() {
		return this.a1 == null ? "" : this.a1;
	}

	public void setA1(String a1) {
		this.a1 = a1;
	}

	public String getA2() {
		return this.a2 == null ? "" : this.a2;
	}

	public void setA2(String a2) {
		this.a2 = a2;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
