package com.my.bean;

// Generated 2014-3-7 19:32:19 by Hibernate Tools 3.4.0.CR1

/**
 * Temp001 generated by hbm2java
 */
public class Temp002 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer temp002id;
	private String f1;
	private String f2;
	private String f3;
	private String f4;
	private String f5;
	private String f6;
	private String f7;
	private String f8;
	private String f9;
	private String fa;
	private String fb;
	private String fc;
	private String fd;

	public Temp002() {
	}

	public Integer getTemp002id() {
		return this.temp002id;
	}

	public void setTemp002id(Integer temp002id) {
		this.temp002id = temp002id;
	}

	public String getF1() {
		return this.f1 == null ? "" : this.f1;
	}

	public void setF1(String f1) {
		this.f1 = f1;
	}

	public String getF2() {
		return this.f2 == null ? "" : this.f2;
	}

	public void setF2(String f2) {
		this.f2 = f2;
	}

	public String getF3() {
		return this.f3 == null ? "" : this.f3;
	}

	public void setF3(String f3) {
		this.f3 = f3;
	}

	public String getF4() {
		return this.f4 == null ? "" : this.f4;
	}

	public void setF4(String f4) {
		this.f4 = f4;
	}

	public String getF5() {
		return this.f5 == null ? "" : this.f5;
	}

	public void setF5(String f5) {
		this.f5 = f5;
	}

	public String getF6() {
		return this.f6 == null ? "" : this.f6;
	}

	public void setF6(String f6) {
		this.f6 = f6;
	}

	public String getF7() {
		return this.f7 == null ? "" : this.f7;
	}

	public void setF7(String f7) {
		this.f7 = f7;
	}

	public String getF8() {
		return this.f8 == null ? "" : this.f8;
	}

	public void setF8(String f8) {
		this.f8 = f8;
	}

	public String getF9() {
		return this.f9 == null ? "" : this.f9;
	}

	public void setF9(String f9) {
		this.f9 = f9;
	}

	public String getFa() {
		return this.fa == null ? "" : this.fa;
	}

	public void setFa(String fa) {
		this.fa = fa;
	}

	public String getFb() {
		return this.fb == null ? "" : this.fb;
	}

	public void setFb(String fb) {
		this.fb = fb;
	}

	public String getFc() {
		return this.fc == null ? "" : this.fc;
	}

	public void setFc(String fc) {
		this.fc = fc;
	}

	public String getFd() {
		return this.fd == null ? "" : this.fd;
	}

	public void setFd(String fd) {
		this.fd = fd;
	}
}
